spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - file:/app/config/core/{application}
            - file:/app/config/infra/{application}
            - file:/app/config/stats-service/{application}

server:
  port: 0

eureka:
  instance:
    hostname: config-server
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/