spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**,/users/{userId}/events/{eventId}/requests/**

        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/{commentId}/**,/users/{userId}/comments/**,/events/{eventId}/comments,/comments/{commentId}

        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**,/users/{userId}/events/**,/events/**,/admin/categories/**,/categories/**,/admin/compilations/**,/compilations/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

server:
  port: 8080